version: "3.8"

services:

  mysql:
    platform: linux/x86_64
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - data:/var/lib/mysql
    env_file: 
    - ./mysql.env
  
  strapi:
    build: .
    volumes:
      - uploads:/app/public/uploads
    env_file: 
      - ./.env
    ports:
      - '1337:1337'
    depends_on:
      - mysql

volumes:
  uploads:
  data: